// const UserActionTypes = {
//     LOGIN_USERS_START: 'LOGIN_USERS_START',
//     LOGIN_USERS_SUCCESS: 'LOGIN_USERS_SUCCESS',
//     LOGIN_USERS_FAILURE: 'LOGIN_USERS_FAILURE',
//     LOGOUT_USERS_START: 'LOGOUT_USERS_START',
//     LOGOUT_USERS_SUCCESS: 'LOGOUT_USERS_SUCCESS',
//     LOGOUT_USERS_FAILURE: 'LOGOUT_USERS_FAILURE',
//     REGISTER_USERS_START: 'REGISTER_USERS_START',
//     REGISTER_USERS_SUCCESS: 'REGISTER_USERS_SUCCESS',
//     REGISTER_USERS_FAILURE: 'REGISTER_USERS_FAILURE',
// }

// export default UserActionTypes;