const ActionTypes = {
    READ_PRODUCTS_START: 'READ_PRODUCTS_START',
    READ_PRODUCTS_SUCCESS: 'READ_PRODUCTS_SUCCESS',
    READ_PRODUCTS_FAILURE: 'READ_PRODUCTS_FAILURE',
}

export default ActionTypes;